#!/bin/sh
#模式一
brctl addbr br0
brctl addif br0 eth$1
brctl addif br0 eth$2

if [ $# = 2 ]

then
echo "br0 have build"
alias ifconfig="/sbin/ifconfig"
RXpre00=$(ifconfig eth$1 | grep bytes | awk 'NR==1 {print $5}')
TXpre00=$(ifconfig eth$2 | grep bytes | awk 'NR==2 {print $5}')
while true; do
sleep 1
RXnext=$(ifconfig  eth$1 | grep bytes | awk 'NR==1 {print $5}')
TXnext=$(ifconfig  eth$2 | grep bytes | awk 'NR==2 {print $5}')
echo "      RX --- TX"
echo "eth$1  $((RXnext-RXpre00))      $((TXnext-TXpre00))"
echo "eth$2  $((RXnext1-RXpre10))      $((TXnext1-TXpre10))"
done

else
brctl delbr br0
fi



#模式二
a=$(lspci | grep Ethernet | wc -l)
b=2
c=`expr $a / $b `
d=100
e=0
a1=$a
a2=$a
a3=$a
let "a--"

while (($c>=1))
do
brctl addbr br$c
brctl addif br$c eth$a
let "a--"
brctl addif br$c eth$a
let "c--"
let "a--"
done

let "a1--"
while (($a1>=0))
do
RXpre$d=$(ifconfig eth$a1 | grep bytes | awk 'NR==1 {print $5}')
TXpre$d=$(ifconfig eth$a1 | grep bytes | awk 'NR==2 {print $5}')
let "a1--"
let "d++"
done

#a 网卡个数  d 00 初始流量  e 0 next流量
while true; do
e=0
d=100
a2=$a3
let "a2--"

while  (( $a2 >= 0 ))    
do
sleep 1
RXnext$e=$(ifconfig  eth$a2 | grep bytes | awk 'NR==1 {print $5}')
TXnext$e=$(ifconfig  eth$a2 | grep bytes | awk 'NR==2 {print $5}')
echo " RX --- TX"
echo "eth$a2  $((RXnext$e-RXpre$d))      $((TXnext$e-TXpre$d))"
let "e++"
let "d++"
let "a2--"
done

done

# #!/bin/bash



# alias ifconfig="/sbin/ifconfig"


# RXpre00=$(ifconfig eth0 | grep bytes | awk 'NR==1 {print $5}')
# TXpre00=$(ifconfig eth0 | grep bytes | awk 'NR==2 {print $5}')
# RXpre10=$(ifconfig eth1 | grep bytes | awk 'NR==1 {print $5}')
# TXpre10=$(ifconfig eth1 | grep bytes | awk 'NR==2 {print $5}')
# RXpre20=$(ifconfig eth2 | grep bytes | awk 'NR==1 {print $5}')
# TXpre20=$(ifconfig eth2 | grep bytes | awk 'NR==2 {print $5}')
# RXpre30=$(ifconfig eth3 | grep bytes | awk 'NR==1 {print $5}')
# TXpre30=$(ifconfig eth3 | grep bytes | awk 'NR==2 {print $5}')
# RXpre40=$(ifconfig eth4 | grep bytes | awk 'NR==1 {print $5}')
# TXpre40=$(ifconfig eth4 | grep bytes | awk 'NR==2 {print $5}')
# RXpre50=$(ifconfig eth5 | grep bytes | awk 'NR==1 {print $5}')
# TXpre50=$(ifconfig eth5 | grep bytes | awk 'NR==2 {print $5}')
# #RXpre60=$(ifconfig eth6 | grep bytes | awk 'NR==1 {print $5}')
# #TXpre60=$(ifconfig eth6 | grep bytes | awk 'NR==2 {print $5}')
# #RXpre70=$(ifconfig eth7 | grep bytes | awk 'NR==1 {print $5}')
# #TXpre70=$(ifconfig eth7 | grep bytes | awk 'NR==2 {print $5}')

# while true; do


# sleep 1
# RXnext=$(ifconfig  eth0 | grep bytes | awk 'NR==1 {print $5}')
# TXnext=$(ifconfig  eth0 | grep bytes | awk 'NR==2 {print $5}')
# RXnext1=$(ifconfig eth1 | grep bytes | awk 'NR==1 {print $5}')
# TXnext1=$(ifconfig eth1 | grep bytes | awk 'NR==2 {print $5}')
# RXnext2=$(ifconfig eth2 | grep bytes | awk 'NR==1 {print $5}')
# TXnext2=$(ifconfig eth2 | grep bytes | awk 'NR==2 {print $5}')
# RXnext3=$(ifconfig eth3 | grep bytes | awk 'NR==1 {print $5}')
# TXnext3=$(ifconfig eth3 | grep bytes | awk 'NR==2 {print $5}')
# RXnext4=$(ifconfig eth4 | grep bytes | awk 'NR==1 {print $5}')
# TXnext4=$(ifconfig eth4 | grep bytes | awk 'NR==2 {print $5}')
# RXnext5=$(ifconfig eth5 | grep bytes | awk 'NR==1 {print $5}')
# TXnext5=$(ifconfig eth5 | grep bytes | awk 'NR==2 {print $5}')
# #RXnext6=$(ifconfig eth6 | grep bytes | awk 'NR==1 {print $5}')
# #TXnext6=$(ifconfig eth6 | grep bytes | awk 'NR==2 {print $5}')
# #RXnext7=$(ifconfig eth7 | grep bytes | awk 'NR==1 {print $5}')
# #TXnext7=$(ifconfig eth7 | grep bytes | awk 'NR==2 {print $5}')

# echo "      RX --- TX"
# echo "eth0  $((RXnext-RXpre00))      $((TXnext-TXpre00))"
# echo "eth1  $((RXnext1-RXpre10))      $((TXnext1-TXpre10))"
# echo "eth2  $((RXnext2-RXpre20))      $((TXnext2-TXpre20))"
# echo "eth3  $((RXnext3-RXpre30))      $((TXnext3-TXpre30))"
# echo "eth4  $((RXnext4-RXpre40))      $((TXnext4-TXpre40))"
# echo "eth5  $((RXnext5-RXpre50))      $((TXnext5-TXpre50))"
# #echo "eth6  $((RXnext6-RXpre60))      $((TXnext6-TXpre60))"
# #echo "eth7  $((RXnext7-RXpre70))      $((TXnext7-TXpre70))"


# done

