#!/bin/sh
#模式一
a=$(lspci | grep Ethernet | wc -l)
b=2
c=`expr $a / $b `
c1=$c 
while (($c1>=0))
do
ifconfig br$c1 down
brctl delbr br$c1
let "c1--"
done 
brctl addbr br0
brctl addif br0 $1
brctl addif br0 $2
ifconfig br0 up


nun1= "help"
if [ $# = 2 ]

then
echo "br0 have build"
alias ifconfig="/sbin/ifconfig"
RXpre100=$(ifconfig $1 | grep bytes | awk 'NR==1 {print $5}')
TXpre100=$(ifconfig $1 | grep bytes | awk 'NR==2 {print $5}')
RXpre101=$(ifconfig $2 | grep bytes | awk 'NR==1 {print $5}')
TXpre101=$(ifconfig $2 | grep bytes | awk 'NR==2 {print $5}')
while true; do
sleep 1
RXnext0=$(ifconfig  $1 | grep bytes | awk 'NR==1 {print $5}')
TXnext0=$(ifconfig  $1 | grep bytes | awk 'NR==2 {print $5}')
RXnext1=$(ifconfig  $2 | grep bytes | awk 'NR==1 {print $5}')
TXnext1=$(ifconfig  $2 | grep bytes | awk 'NR==2 {print $5}')
echo "      RX --- TX"
echo "$1  $((RXnext0-RXpre100))      $((TXnext0-TXpre100))"
echo "$2  $((RXnext1-RXpre101))      $((TXnext1-TXpre101))"
done

elif  [ $1 = $num1 ]
then 
echo "sh shuzu4.sh etha ethb -------build birdge and test these devices   "
echo "sh shuzu4.sh ------------buid birdge for all eth  and test these device  " 
echo  "sh shuzu 4.sh  help ------------request the help "
else
brctl delbr br0
fi


#模式二(数组)
a=$(lspci | grep Ethernet | wc -l)
echo "total eth device is $a"
b=2
c=`expr $a / $b `
d=100
e=0
a1=$a
a2=$a
a3=$a
c1=$c 
while (($c1>=0))
do
ifconfig br$c1 down
brctl delbr br$c1
let "c1--"
done 
let "a--"
while (($c>=1))
do
brctl addbr br$c
brctl addif br$c eth$a
let "a--"
brctl addif br$c eth$a
ifconfig br$c up
let "c--"
let "a--"
done

let "a1--"
while (($a1>=0))
do
RXpre[$d]=$(ifconfig eth$a1 | grep bytes | awk 'NR==1 {print $5}')
TXpre[$d]=$(ifconfig eth$a1 | grep bytes | awk 'NR==2 {print $5}')
let "a1--"
let "d++"
done

#a 网卡个数  d 00 初始流量  e 0 next流量
while true; do
e=0
d=100
a2=$a3
let "a2--"
sleep 1
echo " RX --- TX"
while  (( $a2 >= 0 ))    
do
#sleep 1
RXnext[$e]=$(ifconfig  eth$a2 | grep bytes | awk 'NR==1 {print $5}')
TXnext[$e]=$(ifconfig  eth$a2 | grep bytes | awk 'NR==2 {print $5}')
#echo " RX --- TX"
echo "eth$a2  $((RXnext[$e]-RXpre[$d]))      $((TXnext[$e]-TXpre[$d]))"
let "e++"
let "d++"
let "a2--"
done

done
